$("#load").on('click', function () {
    randomEverything.randomAbout(loadRandomAbout)
    randomEverything.randomFriendGenerator(loadRandomFreinds)
    randomEverything.randomPokemon(loadRandomPokemon)
    randomEverything.randomQuoteGenerator(loadRandomQuote)
    randomEverything.randomUserGenerator(loadRandomUser)
})
$("#display").on('click', function () {
    $(".user-container").empty()
    $(".quote-container").empty()
    $(".pokemon-container").empty()
    $(".meat-container").empty()
    $(".friends-container").empty()
    rend.renderUser(loadRandomUser)
    rend.renderAbout(loadRandomAbout)
    rend.renderFriends(loadRandomFreinds)
    rend.renderPokemon(loadRandomPokemon)
    rend.renderQuote(loadRandomQuote)
})